#list all usuarios
GET http://localhost:5000/usuario

#find usuario by id
GET http://localhost:5000/usuario/{id}

#add new usuario
POST http://localhost:5000/usuario
Content-Type: application/json
{
    "nome": "string",
    "email": "string",
    "senha": "string",
    "curso": "string",
    "departamento": "string",
}

#update usuario
PUT http://localhost:5000/usuario/{id}
Content-Type: application/json
{
    "nome": "string",
    "email": "string",
    "senha": "string",
    "curso": "string",
    "departamento": "string",
}
#delete usuario
DELETE http://localhost:5000/usuario/{id}

